# Generated by Django 4.1.4 on 2022-12-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Note',
        ),
    ]
